### ISSUE TITLE
Problem when used with react-native-device-info

### ISSUE THREAD

**Issue by bufke** [airbnb/react-native-maps#1005] opened 2017-01-31 22:47 UTC
Strange problem. If both maps and device-info are linked I get this when starting the app.

http://pastebin.com/e4grAUXa

Unlinking device-info makes the app work again - but you'll notice the stack trace points to com.airbnb.android.react.maps.AirMapManager

**Comment by gdancel** [comment] 2017-02-04 15:33
Hi, I made a temporary fix for this. The problem is due to the different versions of google play services that the two libraries are using.
https://github.com/gdancel/react-native-device-info

**Comment by lelandrichardson** [comment] 2017-03-27 17:07
Duplicate of #1028

**Closed by lelandrichardson** 2017-03-27 17:07 UTC
