### ISSUE TITLE
"'default' not found" issue after update to RN 0.43.3

### ISSUE THREAD

**Issue by MichelDiz** [airbnb/react-native-maps#1241] opened 2017-04-13 23:58 UTC
It says:
Could not resolve all dependencies for configuration ':app:_debugApk'.
   > Configuration with name 'default' not found.

when I comment the React-native-maps lines it compiles normally.

It has too:
warning "react-native-maps@0.14.0" has incorrect peer dependency "react@>=15.4.0".

follow:
    "react-native-maps": "^0.14.0",
  //  compile project(':react-native-maps')

//include ':react-native-maps'
//project(':react-native-maps').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-maps/android/')

//import com.airbnb.android.react.maps.MapsPackage;

//       new MapsPackage()

Thanks - Best Regards xD

**Comment by iiitmahesh** [comment] 2017-04-14 09:54
it is bug in react-native-maps @14 

@MichelDiz  android folder not available in ../node_modules/react-native-maps/android. by copying android you will get it.

--> create android folder move . move all below folders to android.
 
![screenshot from 2017-04-14 15-22-56](https://cloud.githubusercontent.com/assets/13597781/25040338/5254153c-2126-11e7-9061-6ee4c486f965.png)

**Comment by MichelDiz** [comment] 2017-04-14 22:11
I downgrade to RN 0.43.0 and Works oO

**Comment by Seprum** [comment] 2017-04-14 22:40
Have wasted mine evening trying to make latest version build and I managed to do it.
Basically you need to manually link react-native-maps to your app using instruction, but in `settings.gradle`
you should add
`project(':react-native-maps').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-maps/lib/android')`
instead of
`project(':react-native-maps').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-maps/android')`
(Notice **lib** directory before **android**)
Note: I guess, auto linking with `react-native link react-native-maps` doesn't work because of no `android` directory located in `node_modules/react-native-maps`. Hope it will be fixed soon.

**Comment by MichelDiz** [comment] 2017-04-15 01:07
Many thanks! I gonna try out soon!

**Comment by robgev** [comment] 2017-04-15 22:03
@Seprum I got the same error after doing what you said. Linking is not working as you mentioned.

**Comment by andrewkvavlewhite** [comment] 2017-04-17 14:09
@robgev What he's saying is that because of the path not conforming to react-native standards, the command "react-native link" will not link anything for android. Have you gone through the manual installation process provided [here](https://github.com/airbnb/react-native-maps/blob/master/docs/installation.md#android)?

**Comment by robgev** [comment] 2017-04-17 15:11
@andrewkvavlewhite I fixed it by manually doing all the steps in installation and troubleshooting. Any idea when this will be fixed?

**Comment by npomfret** [comment] 2017-05-08 08:39
I'm still getting `Error:Configuration with name 'default' not found.`  My package.json is pointing at master:

`"react-native-maps": "git+https://github.com/airbnb/react-native-maps.git",`

My `settings.gradle` looks like this:

```
include ':react-native-maps'
project(':react-native-maps').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-maps/lib/android')
```

And my `app/build.gradle` is this:

```
    compile(project(':react-native-maps')){
        exclude group: 'com.google.android.gms', module: 'play-services-base'
        exclude group: 'com.google.android.gms', module: 'play-services-maps'
    }
```

What have I missed?

```
ls ../node_modules/react-native-maps/lib/android
build.gradle                    gradle-maven-push.gradle        gradlew                         src
gradle                          gradle.properties               gradlew.bat

```

**Comment by andrewkvavlewhite** [comment] 2017-05-08 08:57
@npomfret So I haven't installed the latest version yet, but I looked at the install instructions and it looks like you excluded their included play services modules and didn't specify any alternatives.

> If you have a different play services than the one included in this library, use the following instead (switch 10.0.1 for the desired version):

```
...
dependencies {
    ...
    compile(project(':react-native-maps')){
        exclude group: 'com.google.android.gms', module: 'play-services-base'
        exclude group: 'com.google.android.gms', module: 'play-services-maps'
    }
    compile 'com.google.android.gms:play-services-base:10.0.1'
    compile 'com.google.android.gms:play-services-maps:10.0.1'
}
```

You might not need to exclude those modules. Are you doing that for a reason?

**Comment by npomfret** [comment] 2017-05-08 09:00
Sorry, I have got these in (just missed them out in my post).  The problem is that gradle can't find the build file in the new location for some reason.  It's definitely there...

**Comment by andrewkvavlewhite** [comment] 2017-05-08 09:18
Got it. Did you go through the Troubleshooting section on the installation page? When paths and packages are inexplicably not syncing up right, many times caching is the culprit. The Troubleshooting section mentions:

> Clean the cache :
> 
```
watchman watch-del-all
  npm clean cache
```
> When starting emulator, make sure you have enabled Wipe user data.
> 
> Run react-native run-android
> 
> If you encounter com.android.dex.DexException: Multiple dex files define Landroid/support/v7/appcompat/R$anim, then clear build folder.
> 
 ```
 cd android
 ./gradlew clean
 cd ..
```
> If you are using Android Virtual Devices (AVD), ensure that Use Host GPU is checked in the settings for your virtual device.
> 
> If using an emulator and the only thing that shows up on the screen is the message: [APPNAME] won't run without Google Play services which are not supported by your device., you need to change the emulator CPU/ABI setting to a system image that includes Google APIs. These may need to be downloaded from the Android SDK Manager first.

Have you cleaned gradle? Reset watchman? Wiped the emulator (if you're using one)? Sorry, it's just  hard to know exactly what it is, you definitely have followed the install instructions. If all else fails, see if you can build it successfully in a fresh project

**Comment by npomfret** [comment] 2017-05-08 09:34
Thanks for the reply.  Can't do a `gradle clean` because it thinks the gradle file is broken!  So tried `rm -rf node_modules && npm install && react-native start`, but still no luck.

Also, tried the watchman stuff...

**Comment by henrikra** [comment] 2017-05-09 13:21
@felipecsl This can be closed

**Closed** 2017-05-09 18:01 UTC
