### ISSUE TITLE
Is this working at china?

### ISSUE THREAD

**Issue by neo125874** [airbnb/react-native-maps#1244] opened 2017-04-15 04:42 UTC
as title, i want to ask about will this <MapView> component work at china?

**Comment by guoliang1206** [comment] 2017-04-17 01:16
yes

**Comment by neo125874** [comment] 2017-04-17 01:32
@guoliang1206 but this use the google map, but china blocks the google service, doesn't it?

**Comment by guoliang1206** [comment] 2017-04-17 01:34
@neo125874  yes, so you need config your network,   use VPN or SS

**Comment by neo125874** [comment] 2017-04-17 01:38
@guoliang1206 if we publish the logistic drivers, have to ask them to config their phones one by one, is it?

**Comment by guoliang1206** [comment] 2017-04-17 01:43
I think a way that the  client can access google service via your server, but this way is too complicated. I suggest you don't use Google Map in China, the cost is too much.

**Comment by neo125874** [comment] 2017-04-17 01:46
@guoliang1206  so the final solution is to give up using this component which is g-map based, right?

**Comment by guoliang1206** [comment] 2017-04-17 01:52
I don't know the situation about Android, but on iOS platform ,react-native-maps  supported  native map -- Amap , I guess  it  on android as work well as iOS, you can try it .

**Comment by neo125874** [comment] 2017-04-17 02:16
@guoliang1206  is the amap you mentioned means china's gaode map?  or the apple's native map only?  thanks for your reply!

**Comment by guoliang1206** [comment] 2017-04-17 02:19
@neo125874  Apple's native map .

**Comment by HuiguangChu** [comment] 2017-07-12 12:00
Have you solved this g-based map issue?@neo125874  I have the same issue, do you have anything to share? Thank you

**Comment by neo125874** [comment] 2017-07-12 13:13
@HuiguangChu sure, i tried the mapbox instead, it support most feature as this lib, maybe you could give it a try. hope it helps

**Comment by HuiguangChu** [comment] 2017-07-12 13:27
Thank you.  I am trying with mapboxl-gl as well. But I am wondering, how  qiongyou can access the aboard map on their web/app. Do you have any clue? @neo125874

**Comment by felipecsl** [comment] 2017-07-18 06:50
Duplicate of #1477

**Closed by felipecsl** 2017-07-18 06:50 UTC

**Comment by stephenjen** [comment] 2017-12-23 00:31
Surprisingly, I've found that this module works in China without VPN on both iOS and Android devices. Our team has tested the mapping feature of our app numerous times across a period of 2 months from Shanghai, and it works for us.

The problem with our testing is it was all done on US purchased pure Android devices, or devices with Google Play installed over VPN. This module does not work if Google Play Services is not installed.

Is there a workaround for this problem?

**Comment by liuliu66666** [comment] 2018-01-03 10:20
This has been bothering me for a long  time.When I use the react-native-maps in China (already using a VPN),but it was gaode map.????

**Comment by DavidBBG** [comment] 2018-01-10 02:42
Sorry for the dumb Q @stephenjen but just saw https://www.google.cn/maps is working in China without VPN. Has this been the case for a while and is integration different from https://www.google.com/maps?

**Comment by stephenjen** [comment] 2018-01-10 05:04
My colleague just checked and https://www.google.cn/maps works today in Shanghai.

**Comment by neo125874** [comment] 2018-01-10 07:16
@stephenjen hello, so most of phones purchased at china would be without the google service, and could result this library not working, right?

**Comment by stephenjen** [comment] 2018-01-10 11:16
@neo125874 it is my impression that this library requires google play service.  The couple phones we tried that were purchased in China did not have google play service, and the module did not work

**Comment by rborn** [comment] 2018-01-10 11:18
@stephenjen @neo125874 the lib **does** require google play service so the devices that don't have it won't work, no matter where they are purchased from.

**Comment by neo125874** [comment] 2018-01-11 03:25
@rborn thanks, and i think @stephenjen was telling about that the phones from china maybe remove  the google service from them, so most of people could not use the app which  contains this lib.

**Comment by rborn** [comment] 2018-01-11 10:40
@neo125874 sorry for not being clear, yes this is what I meant, but this happens in other parts of the world too :)
