### ISSUE TITLE
Is airbnb still on this project?

### ISSUE THREAD

**Issue by henrikra** [airbnb/react-native-maps#1280] opened 2017-04-28 07:49 UTC
I feel like this library has been abandoned since the collaborators are not fixing even the critical bugs. There is 502 issues and 37 prs open. This is not normal. There are at least two very critical bugs caused this library to crash for many users. They are these: https://github.com/airbnb/react-native-maps/issues/271 https://github.com/airbnb/react-native-maps/issues/1227

Could you please tell if you are not going to do this project very often? If yes could you consider adding collaborators who are actually active and who do reviews prs and make new releases

**Comment by hrastnik** [comment] 2017-04-28 18:21
It's gets worse... The official RN docs recommends this component since their MapView component is depracated and supports only iOS.

Source: https://facebook.github.io/react-native/docs/mapview.html

**Comment by babenzele** [comment] 2017-04-29 02:28
A software engineer at airbnb committed to master 24 days ago.

<img width="653" alt="screen shot 2017-04-28 at 7 26 59 pm" src="https://cloud.githubusercontent.com/assets/3578574/25552212/b529e2d6-2c48-11e7-8d1a-e6f60390b427.png">

https://github.com/airbnb/react-native-maps/commits/master

**Comment by henrikra** [comment] 2017-04-30 01:18
@babenzele Yeah that is the problem :D

**Comment by babenzele** [comment] 2017-04-30 08:11
What's the problem? 24 days too long for comfort? OSS projects don't fix themselves, take a dive in there and submit a PR.

**Comment by Exilz** [comment] 2017-04-30 08:14
The problem is not the lack of commit for airbnb themselves. As you said, community can take care of this project and fix the most important stuff. We don't expect them to dedicate an employee's time adding feature to a community plugin.
As @henrikra said, the pull requests aren't supervised enough. Very interesting changes have been submitted ages ago and still nothing happened.

**Comment by babenzele** [comment] 2017-04-30 08:25
Hmm, let's try get some good ones merged. Could you link some of the better ones?

**Comment by henrikra** [comment] 2017-05-01 09:13
@babenzele All PR's related to crashes are priority one in my opinion. Since if the maps is crashing often the features does not matter :)

**Comment by babenzele** [comment] 2017-05-01 11:16
Only one PR comes up when I search "crash" (https://github.com/airbnb/react-native-maps/pull/1273) and it was opened 5 days ago. 

https://github.com/airbnb/react-native-maps/pulls?utf8=%E2%9C%93&q=is%3Apr%20is%3Aopen%20crash

**Comment by alreadysabbir** [comment] 2017-05-01 20:26
Critical PR like #1249 #1193 #1226 #1200 is not yet merged!
Please add more collaborator at least!

**Comment by alreadysabbir** [comment] 2017-05-01 20:27
Not even docs improvement PR 😞

**Comment by henrikra** [comment] 2017-05-02 08:41
@babenzele For example #1287 this issues is making whole map crash on RN 0.44

**Comment by jeveloper** [comment] 2017-05-02 11:17
@lelandrichardson  Leland, would you consider moving the project to community or add collaborators . Thank you

**Comment by GShotwell** [comment] 2017-05-02 13:31
+1

**Comment by Falconerd** [comment] 2017-05-03 04:09
I don't know if this will help anyone, but I was having huge issues getting this to work reliably across both platforms. I ended up using these versions:

```
react-native@0.42.3
react-native-maps@0.13.0
```

Hopefully that helps someone.

**Comment by kelset** [comment] 2017-05-03 09:00
I have it working properly with RN 0.43, but can't figure out a way to make it work with 0.44.
I agree on the more collabs need.

(To give a glimmer of hope, a while back Leland told me that they were preparing a huge release for RNMaps but I can't find the tweet anymore)

**Comment by james2406** [comment] 2017-05-05 11:02
It looks like a few commits were made to the master branch, which should fix the 0.44 issue https://github.com/airbnb/react-native-maps/commit/4b861c949a079a393f48a485943d3a506a151ac0

**Comment by felipecsl** [comment] 2017-05-05 17:30
[Airbnb engineer here]
Indeed we're very resource constrained right now and have not given this library the attention it needs/deserves. I'll help triaging issues/PRs in the next couple days and we'll look into adding more contributors soon. Please bear with us in the meantime 😄

**Comment by jeveloper** [comment] 2017-05-05 18:10
Thanks @felipecsl , appreciate you letting us know and thanks to AirBnB 

btw , the current committs in the past 24 hours resolved a breaking problem for RN 44, any chance you can tag a version and push it up to npm , that would be great.

**Comment by felipecsl** [comment] 2017-05-08 19:03
@christopherdro it seems like you already uploaded 0.15.0 to next 4 days ago? I just promoted that to latest!

**Closed by felipecsl** 2017-05-08 19:03 UTC

**Comment by EricPKerr** [comment] 2017-08-29 15:55
This deserves to have a much larger discussion, but I feel like this issue should be re-opened.  There are a dozen issues that mention `initialRegion`,`region`, and `onRegionChange` alone, and they've become noticeably more problematic.

This should be moved to react-native-community (or even RN core) so more people can openly contribute and make this better. It's too critical of a project to not have active core members monitoring Issues and Pull Requests.

**Comment by felipecsl** [comment] 2017-08-29 17:49
@EricPKerr reopening this issue will not help with fixing those problems you mentioned. We're happy to add more contributors to the project and/or move it to a different org (eg.: `react-native-community`, as you suggested). If anyone who is familiar with the code, is using it in production and is committed to maintaining/improving this, please step forward and we'll be happy to work with you to add as maintainers. If you prefer moving it, I can help with that too!

**Comment by alvelig** [comment] 2017-12-05 02:46
@felipecsl ME! ***stepping forward*** At least iOS is familiar to me. And I am using it for production.

**Comment by felipecsl** [comment] 2017-12-05 05:27
@alvelig the current plan is to move this repo to the `react-community` org. We're waiting on someone with enough permissions to help with that transition.

**Comment by sasan-ebrahimi** [comment] 2020-06-14 07:42
I tried many things and finally I found a solution. Worked for me on Android. Just putting Image tag inside a Text tag

<Text><Image .../></Text>
