### ISSUE TITLE
Custom Marker Oversize

### ISSUE THREAD

**Issue by felangga** [airbnb/react-native-maps#1476] opened 2017-07-14 02:43 UTC
I created an image for custom marker and it works fine on debug mode. 
But when I build with release mode in xcode, the marker become oversize, it's too way big.

**Comment by vinagrito** [comment] 2017-07-16 08:09
@felangga Seems like a duplicate of [this issue](https://github.com/airbnb/react-native-maps/issues/1422).
@christopherdro I think this can be closed.

**Closed** 2017-07-17 04:53 UTC
