### ISSUE TITLE
Android: first instance of the map overlaps everything when have another map in a different scene.

### ISSUE THREAD

**Issue by kakbeya** [airbnb/react-native-maps#453] opened 2016-08-09 13:04 UTC
Hi guys, 

I know you have lots of issues already to work on, but here is another one.

I'm using RN 0.31 with latest maps and was finally able to get my map to show up on Android with a Browser Key.

I also use react-native-router-flux and I have two scenes with maps. When I switch to the second scene, the map from the first one is frozen on top of it. I can tap/drag the map behind it and everything, but can't see what I am tapping because of this lag. If I remove the map from the second screen - everything works fine.

Any ideas or workarounds?

Thanks, 
Alex.

**Comment by jeveloper** [comment] 2016-08-09 14:25
I filed a ticket for this , both here and in RNRF git, folks are taking it easy ,  i rolled back to rn 28 
tried many ways
if you do find a work around (basically demounting mapview so its completely gone when navigation state changes , please share.

thanks

**Comment by kakbeya** [comment] 2016-08-09 14:43
@jeveloper thanks,

I just was able to do it with changing my second scene type to:

**type="replace"**

Not the best solution as it removes the smooth transition, but works!

**Comment by jeveloper** [comment] 2016-08-09 15:22
Yeah i did observe that , but obviously when you want to stack navigation and want to have to a back arrow , it won't work.
Yes it also completely unmounts the view and mapview is actually a heavy component ( takes a bit of time to render on older devices)

**Comment by morrigan** [comment] 2016-08-10 17:25
+1, same with NavigationExperimental and RN 0.28

**Comment by jeveloper** [comment] 2016-08-10 17:37
@morrigan i believe 29 or 30 has a fix for it. 
By unresponsive do you mean that its basically appearing on top of a previous view?

**Comment by danscan** [comment] 2016-08-12 23:10
I'm having this same issue on a project that uses `react-native-router-flux`.  Adding `type="replace"` to the affected scenes works as a workaround.

**Comment by jeveloper** [comment] 2016-08-12 23:41
@danscan  can you confirm which version of rnrf you're using , latest is 34 and which RN 

thanks

**Comment by danscan** [comment] 2016-08-16 22:50
@jeveloper Sorry for the delay.  I'm using  `react-native-router-flux@3.30.9` and `react-native@0.29.2`

**Comment by jeveloper** [comment] 2016-08-16 22:55
No problem @danscan  , let me know if latest RNRF will work

**Comment by danscan** [comment] 2016-08-16 23:10
@jeveloper Updating to `react-native-router-flux@3.34.0` doesn't affect this issue.

**Comment by olegpesok** [comment] 2016-08-18 21:08
I've narrowed down odd map overlay behavior to this PR: https://github.com/lelandrichardson/react-native-maps/pull/363. Before this PR maps work fine, after I'm getting odd overlay behavior. This is running react-native 0.28 and RNRF 3.34.0. I'm going to try to pull out this commit and patch on top of maps 0.7.1 and see if I can get things working ok in 0.29.2.

**Comment by jeveloper** [comment] 2016-08-18 21:31
Thanks @olegpesok   , Spasibo
But i'm looking at 363 and its mainly a way to upgrade due to changes RN 29 made for android by passing appcontext as oppose to activity, etc.
Dan mentioned that a map is rendered in front of another (Z axis )

**Comment by olegpesok** [comment] 2016-08-18 22:56
@jeveloper I won't even pretend to understand enough Android dev to say why these things are related, but I DID manage to fix the problem here: https://github.com/olegpesok/react-native-maps/commit/030ea042dfd1b7384d192642ec0d3a817b662b7a

This is running RNRF 3.34.0, RN 0.29.2, and react-native-maps 0.7.1 (with my patch).

This isn't production quality at all. I can imagine all sorts of ways this would break in a real app, but for my test case it did resolve the issue. Maybe someone more knowledgeable can figure out a more permanent fix.

**Comment by pellepersson** [comment] 2016-08-22 10:11
@olegpesok - I got this to work on RN 0.31 with one minor change. I kept the reactContext.getBaseContext() as an argument for new AirMapManager() in MapsPackage.java. Great job!

I would love to know more about what you believe needs to be done to use this in production..? Or is there perhaps someone else around that knows more about Android development that could tell what risks or issues this solution could lead to..?

**Comment by olegpesok** [comment] 2016-08-23 17:34
@pellepersson Well, I'm basically creating a singleton that's holding a reference to the main activity as long as the app is running. Ideally you need to remove that reference whenever the main activity needs to be 'unmounted' or you risk memory leaks. I think for most simple RN apps thats not an issue since the main activity is probably the only activity and will exist as long as the app is running.

**Comment by jeveloper** [comment] 2016-08-23 18:35
Hey Oleg and @pellepersson  , awesome, thats a small change :) 
Can you make a pull request on that @lelandrichardson and few others who approve hopefully will notice

**Comment by whs** [comment] 2016-08-24 09:46
Seems that react-native is getting `getCurrentActivity` support in v32: https://github.com/facebook/react-native/commit/760656461197605ee26769ed73989f78e4753038

**Comment by jeveloper** [comment] 2016-08-24 22:41
Check this out, someone made a pull request

https://github.com/lelandrichardson/react-native-maps/pull/449/commits/5187d4f33aea0009363f72ae4aaacc9b0d7829c7

**Comment by veedeo** [comment] 2016-08-29 12:17
Hey guys, any update on this issue? Is there a workaround?

**Comment by jeveloper** [comment] 2016-08-29 15:01
@veedeo I hope they'll take in pull requests that are pending, not much support for this project for some reason :(

**Comment by pellepersson** [comment] 2016-08-29 18:29
Today we tried to run the pull request that @jeveloper is linking to ([https://github.com/lelandrichardson/react-native-maps/pull/449/commits/5187d4f33aea0009363f72ae4aaacc9b0d7829c7]) and the map view feels a bit more light weight now compared to the other solution we are discussing above.

**Comment by jeveloper** [comment] 2016-08-29 20:25
Hey @pellepersson , what do you mean by feels a bit more light weight? , less memory use?
and switching between multiple mapviews is good? fast?

thanks

**Comment by pellepersson** [comment] 2016-08-30 03:23
@jeveloper - yes I was thinking about the memory usage. multiple mapviews works for both solutions.

**Comment by veedeo** [comment] 2016-08-30 05:46
@pellepersson greate news, can you check if this solves swiping issues with a MapView beeing placed into scrollable container. In my case its a RNRF component with direction="vertical", but maybe placing it into a scrollview will show same problems

**Comment by jeveloper** [comment] 2016-08-30 14:27
@pellepersson  thank you for confirming that.

I wonder when folks on this project will start accepting pull requests, they seem to ignore it

**Comment by pellepersson** [comment] 2016-08-31 16:31
@veedeo - sorry, but I don't have time for that. It is not that hard to do it yourself though... just refer to the pull request in your app's "package.json":

`"react-native-maps": "https://github.com/lelandrichardson/react-native-maps#5187d4f33aea0009363f72ae4aaacc9b0d7829c7"`

and do what @olegpesok describes above to make sure it is the local build that is being compiled in "app/build.gradle":

`
...
//compile "com.airbnb.android:react-native-maps:0.7.1"
compile project(':react-native-maps')
...
`

**Comment by spikebrehm** [comment] 2016-08-31 18:08
We think this may be fixed by this PR that was just merged: #449.  Perhaps you can verify?

**Comment by jeveloper** [comment] 2016-08-31 18:45
@olegpesok @pellepersson  Hey guys, it feels like im the guy that connects issues , pulls and provides context. Hope this issue will resolve multiple mapviews between navigations. 
Can you confirm if it did within your project.

Thanks

**Comment by veedeo** [comment] 2016-08-31 18:49
@jeveloper I do have multi maps in my proj to, how can I test this merge?

**Comment by jeveloper** [comment] 2016-08-31 19:22
And you are experiencing that issue , right? where the same map is displayed (overlayed on top of ) 

I suggest instead of version in package.json, set this "lelandrichardson/react-native-maps" and you'll be using latest master commit

**Comment by veedeo** [comment] 2016-08-31 21:18
Well, Ive updated my proj to latest maps, react and RN and now Intent crashes whenever it tryes to load the map. I wonder how I can see logs, log-android doesnt show this error

**Comment by jeveloper** [comment] 2016-09-01 00:26
Open Android Studio with connected device , switch to monitor , you can see Error level and you'll see java error with stack trace

btw dont update gradle or anything Android studio suggests , it'll break your project :)

**Comment by veedeo** [comment] 2016-09-01 06:11
Looks like its related to #502 

> java.lang.NoSuchMethodError: #No direct method <init>(IJ)V in class Lcom/facebook/react/uimanager/events/Event; or its super classes (declaration of 'com.facebook.react.uimanager.events.Event' appears in /data/app/com.tandem-1/base.apk)
	at com.airbnb.android.react.maps.RegionChangeEvent.<init>(RegionChangeEvent.java:16)
	at com.airbnb.android.react.maps.AirMapView$8.onCameraChange(AirMapView.java:220)
	at com.google.android.gms.maps.GoogleMap$12.onCameraChange(Unknown Source)
	at com.google.android.gms.maps.internal.zze$zza.onTransact(Unknown Source)
	at android.os.Binder.transact(Binder.java:387)
	at wd.a(:com.google.android.gms.DynamiteModulesB:93)
	at maps.E.a.a(Unknown Source)
	at maps.E.a$1.run(Unknown Source)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5417)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by veedeo** [comment] 2016-09-03 06:40
After updating to latest ver and gradlew clean, Ive managed to run my project, MapView loads much faster now, but overlapping issue is still present

**Comment by ryankask** [comment] 2016-09-03 09:54
I've pulled in master and the overlapping issue is still there.

**Comment by jeveloper** [comment] 2016-09-04 13:17
Hey @olegpesok , have you merged the latest master into your codebase ?
Curious if i misunderstood the fix you proposed.

**Comment by spikebrehm** [comment] 2016-09-06 17:32
Would someone be able to submit a PR that adds a test case to the example app of the overlapping maps issue? It's hard for us to fix this if we can't test it in the example.

**Comment by ryankask** [comment] 2016-09-07 08:25
I'm happy to do this although I'm having trouble running the example app on Android:

```
09-07 09:21:08.265  2526  2526 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: "/data/data/com.airbnb.android.react.maps.ex
ample/lib-main/libgnustl_shared.so" is 32-bit instead of 64-bit
```

When the app starts the above exception is thrown. Is there any instructions on how to run the example app?

**Comment by ryankask** [comment] 2016-09-07 09:38
I've created another example project in my fork: https://github.com/ryankask/react-native-maps/blob/issue-453-android-overlap/example2/

This demonstrates the issue. It seems like the issues is with opacity not being respected. 

While my example is contrived, this can happen in real world apps when tab navigation is used and opacity controls visibility of the focused tab.

**Comment by nktamboli** [comment] 2016-09-07 13:09
Even I am getting the same issue. Is this related to router flux? 

I strongly feel that Router Flux in combination to Map gives the issue of overlay! I have another screen where map is loaded. And that is not within a drawer. That screen doesnt have this issue.

**Comment by jeveloper** [comment] 2016-09-07 13:14
@nktamboli Folks have proven that it wasnt related to router flux
i thought the same

**Comment by ryankask** [comment] 2016-09-07 13:19
I've posted a full sample app above that reproduces the issue. react-native-router-flux is not needed for this issue to show up.

There may be other ways it can manifest itself but this file demonstrates one: https://github.com/ryankask/react-native-maps/blob/issue-453-android-overlap/example2/app.js

**Comment by mynamespace** [comment] 2016-09-07 18:19
react-native-router-flux uses react-native-tabs, not react-native-tab-navigator. What a mess with these names :D

**Comment by ryankask** [comment] 2016-09-07 18:34
Thanks for the correction. 

It used to use react-native-tab-navigator and it now borrows the rendering logic. Here is where it sets the opacity of each tab view: https://github.com/aksonov/react-native-router-flux/blob/master/src/TabbedView.js#L38. This is similar to the example I posted above.

```js
renderScene(navigationState, index) {
    const isSelected = index === this.props.navigationState.index;
    return (
      <View
        key={navigationState.key}
        pointerEvents={isSelected ? 'auto' : 'none'}
        removeClippedSubviews={!isSelected}
        style={[
          styles.scene,
          { opacity: isSelected ? 1 : 0 },
        ]}
      >
        <StaticContainer shouldUpdate={isSelected}>
          {this.props.renderScene(navigationState, index)}
        </StaticContainer>
      </View>
    );
  }
```

**Comment by spikebrehm** [comment] 2016-09-07 18:42
@ryankask:

> I've created another example project in my fork: https://github.com/ryankask/react-native-maps/blob/issue-453-android-overlap/example2/

Thanks for that, that helps! Great small test case.  We'll look into it but we welcome anyone's insight! cc: @felipecsl

**Comment by jeveloper** [comment] 2016-09-07 18:43
Hey @ryankask , appreciate your time on this!

I believe its not bound to be an issue with tabs , its the same issue without tabs as well.
I lost track of 4 issues out there now in relation to this issue (folks don't check existing bugs) 

Someone with knowledge mentioned that Z axis is not updated properly to place the map behind currently rendered view.

I published a test case and description in RNRF github, sorry , should've pasted here for @spikebrehm

**Comment by ryankask** [comment] 2016-09-07 18:49
@jeveloper no problem! It's an interesting issue.

I don't think it's an issue with the tabs but the method used to render the tabs can cause this issue.  Specifically, using opacity to focus a stack of views. The test case I provided above demonstrates that.

I would be surprised if that was the only way to cause the issue but it's a start. I don't know much about Android dev but I'm having a look now 😄

**Comment by spikebrehm** [comment] 2016-09-07 22:54
Here's a potential workaround.  Instead of using `opacity` to hide the map view, try just not rendering it.  Starting with @ryankask's example:

https://github.com/ryankask/react-native-maps/blob/3ccc684901d4d970f4370ee973a160239c9a0da8/example2/app.js#L101

Instead of using `opacity: 0` vs `opacity: 1` to reorder the map:

```js
          <MapView
            style={[styles.map, this.state.visibleMap === 0 && { opacity: 1 }]}
            initialRegion={Region.LONDON}
          />
          <MapView
            style={[styles.map, this.state.visibleMap === 1 && { opacity: 1 }]}
            initialRegion={Region.SAN_FRANSISCO}
          />
```

You could just not render the map if it's not visible:

```js
        { this.state.visibleMap === 0 &&
          <MapView
            style={styles.map}
            initialRegion={Region.LONDON}
          />
        }
        { this.state.visibleMap === 0 &&
          <MapView
            style={styles.map}
            initialRegion={Region.SAN_FRANSISCO}
          />
        }
```

The downside of this approach is that by un-mounting the map, it has to load the tiles again when it's re-mounted, so it's less of a smooth transition.

I'll try to look into why the opacity is an issue in the first place, but that may take some time.  Help would be appreciated.

Re: `opacity` on Android, I noticed that for any non-`1` value, the map tiles disappear completely, however the little `Google` logo in the bottom corner does change in opacity. Here's what `opacity: 0.5` looks like:

<img width="484" alt="screen shot 2016-09-07 at 3 53 47 pm" src="https://cloud.githubusercontent.com/assets/133937/18331396/6bf4387e-7513-11e6-8c47-4397f8f91254.png">

**Comment by ryankask** [comment] 2016-09-08 09:43
Thanks, @spikebrehm, for following up.

I may indeed need to stop rendering the map when the users switches tabs. I've explored some other options such as moving the map off screen off the screen when the users switches tabs. Unmounting might be beneficial regardless in terms of memory usage so I'll look into it.

I'm still curious about what's going on. I overrode `AirMapView#setAlpha()` and can see that it's being called each time I press the button. I threw in a few `#invalidate()`, `#requestLayout()`, and '#forceLayout()' calls there too but I'm a bit out of my element because I've never developed a native Android app.

**Comment by veedeo** [comment] 2016-09-08 10:02
You can simplify your test case by removing the alpha and just putting one MapView on another with little offset. You will see that first MapView will be fully visible, even on the overlapping region of the second map. Try to move 'overlapping' region and you will see that second Map is beeing moved

```
render(){
    return (
       <View style={{flex:1, backgroundColor: 'gray'}}>
         <MapView style={{...StyleSheet.absoluteFillObject, width: 200, height:200}} />
         <MapView style={{...StyleSheet.absoluteFillObject, width: 200, height:200, top: 100, left:100}} />
      </View>
    );
  }
```

**Comment by ryankask** [comment] 2016-09-08 11:12
Good point.

Searching for "android google mapview overlap" reveals quite a few issues so it seems like an upstream bug but I can't be certain.

Here are some I found: 

1. [Android: Maps V2 Map view instances overlap when placed in separate tabs](https://jira.appcelerator.org/browse/TIMOB-14694)
2. [Android Google map v2 in tab Overlapping issue, Multiple map in tab](http://stackoverflow.com/questions/16768174/android-google-map-v2-in-tab-overlapping-issue-multiple-map-in-tab)

I tried using GoogleMapOptions#zOrderOnTop as suggested in one bug report I found but it didn't work.

The solutions mention wrapping the MapView in a View but I don't know enough about it to give it a shot.

Related issue: https://github.com/lelandrichardson/react-native-maps/issues/207

**Comment by spikebrehm** [comment] 2016-09-08 17:24
Good find, @ryankask! From those SO questions you posted, it seems like the fix is:

> The key is to route the lifecycle events of the Fragment to the MapView

Solution discussed here:
http://stackoverflow.com/a/16960527
http://stackoverflow.com/a/16850620

Does anyone with familiarity with Android see how to implement this for `react-native-maps`?

**Comment by felipecsl** [comment] 2016-09-08 22:08
Routin the Activity lifecycle events into the `MapView` didn't fix the issue. I'll keep investigating this and will report back when I have a fix

**Comment by felipecsl** [comment] 2016-09-09 18:59
Ok so I did a bunch of investigation and research on this and here is what I found:
[Apparently](http://stackoverflow.com/a/12570491) multiple `MapView`s on the same `Activity` are not supported by Google Maps on Android and you just shouldn't do it because it most likely won't work. 
Also, therefore, overlapping maps are not supported and that's why the sample code provided in the comments doesn't work.
If you want to achieve some kind of tabbed layout on Android with multiple maps on the same Activity, your best bet is to use the `ViewPagerAndroid` component, which is the "standard" way to do tabs on Android (it uses a `ViewPager` under the hood). 
I've attached a GIF below of how that looks like and a sample code:
![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/190648/18399105/e04a7538-76a5-11e6-8da0-c2be5c45bde5.gif)
Gist with the app.js code: https://gist.github.com/felipecsl/609c83f37ddfcce3b46cddd9e0d6f41f

I'm familiar with how this translates to iOS, but it would probably require some alternative implementation. 

Finally, I'd propose closing this issue as doesn't seem like there's anything for us to do here

**Comment by jeveloper** [comment] 2016-09-09 19:33
Thanks for taking time on this @felipecsl  , appreciate it !

I read your code. So there is no way to use RNRF or other navigation, i wonder if this may mean a slight rewrite for this library. 

Any other work around you might think of ? ViewPagerAndroid feels a bit invasive and requires a different code base if someone is using navigation between views.

**Comment by felipecsl** [comment] 2016-09-09 19:35
Correct, that's a bit unfortunate @jeveloper. I dont have any other ideas since i'm not super familar with the JS ecossystem, @lelandrichardson or @spikebrehm may have other ideas

**Comment by ryankask** [comment] 2016-09-10 07:44
@felipecsl Wow! Thanks for looking into this.

It might actually be straightforward to use ViewPagerAndroid for the tabs by using `ViewPagerAndroid.setPageWithoutAnimation()` and the `scrollEnabled` prop. I think for now I'll just stop rendering the other map when different tab is selected.

Looking at the implementation of ViewPagerAndroid it doesn't seem to use a separate activity so I'm surprised it works.

**Comment by sarovin** [comment] 2016-09-12 15:25
react-native-maps@0.8.2 solves the problem?

**Comment by jeveloper** [comment] 2016-09-12 15:39
no @sarovin , there is a suggestion to use androidpagerview

**Comment by sarovin** [comment] 2016-09-12 16:16
Yes, but i can't use androidpagerview because i use react-native-router-flux.

**Comment by jeveloper** [comment] 2016-09-12 16:24
same for me @sarovin  , i can't really re-engineer the whole app for android specific issue

**Comment by jeveloper** [comment] 2016-09-12 16:26
@felipecsl I forgot to mention to you that this is not an issue with this map version 0.6.0 and RN 28

**Comment by felipecsl** [comment] 2016-09-12 16:55
@jeveloper that's an interesting finding. It could be just that it worked on play services 8.4 but not on 9.4, or something that changed recently in RN that caused this. It could be that it just worked "by accident" but was never officially supported, which seems to be likely the case here.
If you have time, please feel free to keep digging for other solutions!

**Comment by jeveloper** [comment] 2016-09-12 18:03
I can confirm that it works on 9.4 on various devices.
RN 28 + 0.6.0 , with multiple views works like a charm, no accidents :)
Changes in RN 29+ affected something blocking us from upgrading.

**Comment by nktamboli** [comment] 2016-09-13 18:24
I somehow found a catch in this. I am using Router Flux with this and on state change, similar issue happened.

What I did was, the maps which I was supposed to load, had no back button/history. So, I switched to the new map view using Actions.<ActionName>({type: 'reset'}).

In router flux, type='reset' prop unmounts all views from view cache. This unmounts the previous map container and the new map container mounts thereafter, hence keeping only one map in stack.

This is for Router Flux. If anybody is using anything else, may also have such reset feature in their routing. That should do the trick.

However, this is NOT helpful if you want to maintain current view stack. But anyone who wants to switch maps and can compromise with view stack, can use this.

Hope this helps somebody.

**Comment by fdnhkj** [comment] 2016-09-14 08:27
@nktamboli This kind of solution was mentioned by @kakbeya earlier (2nd comment of this issue). But as you say, it won't keep the view stack.

@jeveloper Do you see something suspicious in the release notes of RN 29 https://github.com/facebook/react-native/releases/tag/v0.29.0 ?
This issue is blocking for my rn app. I would be glad to help but I don't really know where to look at.

**Comment by jeveloper** [comment] 2016-09-14 12:27
@fdnhkj It was a few months ago now. I thought it had something to do with navigation changes, but RNRF isnt an issue here it seems (someone proved it with just bare navigation ) 

I recall @olegpesok  forking and testing his changes where he altered a method that was passing activity or app context and that supposedly fixed it, but i haven't heard back from him.

Here is the snippet from RN29 changes:
"Plugins which pass activity reference in the constructor need to be updated to extend ReactContextBaseJavaModule use getCurrentActivity to get the activity reference. This change is backward compatible."

**Comment by sarovin** [comment] 2016-09-14 14:11
Another way is use a modal instead of a second screen.

**Comment by fdnhkj** [comment] 2016-09-17 20:13
Hello!
I investigated a bit more on this issue and found a fix.
As mentioned in the PR https://github.com/airbnb/react-native-maps/pull/589, I tested it with :
``` json
  "dependencies": {
    "react": "15.3.1",
    "react-native": "^0.32.0",
    "react-native-maps": "^0.8.2",
    "react-native-router-flux": "^3.35.0"
  }
```

It could be great if some people facing the same issue could test it also :)

**Comment by jeveloper** [comment] 2016-09-18 15:10
Thanks @fdnhkj , looks like what @olegpesok  experienced, should be good :) 

\

**Comment by veedeo** [comment] 2016-09-21 06:11
@fdnhkj Hey Im trying to use your branch to test the issue but getting this error, any ideas what Im doing wrong?
```
* What went wrong:
A problem occurred configuring project ':app'.
> A problem occurred configuring project ':react-native-maps'.
   > Could not resolve all dependencies for configuration ':react-native-maps:_debugCompile'.
      > Could not find com.google.android.gms:play-services-base:9.4.0.
```

**Comment by veedeo** [comment] 2016-09-21 09:39
@fdnhkj you are the man! Your PR solves overlay issues and the app feels much faster now.
Well done!

**Closed** 2016-09-21 22:23 UTC

**Comment by kakbeya** [comment] 2016-10-02 23:42
Guys,

I have tried the setup mentioned above, but no luck for me. Still seeing the issue. 

`"dependencies": {
    "react": "15.3.1",
    "react-native": "^0.32.0",
    "react-native-maps": "^0.8.2",
    "react-native-router-flux": "^3.35.0"
  }`

Do I need to do something else?

**Comment by joncursi** [comment] 2016-10-03 02:45
I'm also reporting this same issue on Android on react-native-maps 0.8.2.

**Comment by ryankask** [comment] 2016-10-03 05:37
@kakbeya The fix is available (along with several other changes) in 0.9.0-rc.0.

If you only want this specific change the commit is here: https://github.com/airbnb/react-native-maps/commit/89308d8a34e629e8e6afc9041024b9407f977d54

**Comment by jeveloper** [comment] 2016-10-03 15:05
Feel free to close :)

**Comment by kakbeya** [comment] 2016-10-03 15:39
Yup, that fixed it. Thank you!

**Comment by spikebrehm** [comment] 2016-10-03 15:49
👍 fixed in 0.9.0-rc.0.  I'll be releasing 0.9.0 soon.

**Comment by joncursi** [comment] 2016-10-03 16:22
0.9.0-rc.0 indeed seems to have fixed the original issue. However, I noticed a small side-effect. Only the first map rendering contains a marker for the `userLocation`. Every map after that will not does the user's location when specified.

**Comment by gharwood** [comment] 2016-10-26 19:35
Has this issue popped back up for anyone?

I am seeing this on:

```
"react-native": "^0.35.0",
"react-native-maps": "0.9.0-rc.0", (changed it to this after 0.11.0 didn't work)
```

I am using NavigationCardStack from NavigationExperimental and seeing part of the previous scene's map when transitioning to another scene that also has a map.

**Comment by keenltd** [comment] 2016-12-07 10:21
This seems to be occuring for me too. 

```
"react-native": "^0.35.0",
"react-native-router-flux": "^3.36.0",
"react-native-maps": "^0.11.0",
```

Has anybody managed to get to the bottom of this?

**Comment by gharwood** [comment] 2016-12-09 01:18
@keenltd Our work around was to wrap the map component in a conditional based on the current route(or some boolean state). So something like:

```
{ someStateTrue
  ? <MapView />
  : null
}
```

This turned out to be better anyways because it prevented a pretty heavy component from getting rendered in the scene stack. In our case it the MapView + Marker was updating real time based on GPS coords.

Hope it helps.

**Comment by veedeo** [comment] 2016-12-09 07:15
As mentioned earlier fdnhkj/react-native-maps fixes this issue, it also makes MapView much lighter and faster and removes visual glitches when moving the map.
Im not sure if it was merged to master but if not it definitely should be

**Comment by jeveloper** [comment] 2016-12-09 15:37
@veedeo I want to clarify that this issue is officially fixed in branch 0.11 ,0.12 and 0.10.x 

Folks, i recommend adding enablling loader for android, there are crash reports if android itself + google map services did not load component in memory itself , then your app logic will attempt to modify something that's still null or not fully loaded.
cheers

**Comment by joshualcoffee** [comment] 2017-01-10 15:29
This still seems to be an issue using 
"react-native-maps": "0.13.0"  and `NavigationExperimental`
This seems to happen using traditional scenes and modals.
![image](https://cloud.githubusercontent.com/assets/873384/21811987/8a9e9bfc-d71f-11e6-9c04-28688211801d.png)
The map on the left is in the scene "before".  Could you think of any workarounds or something I could look in to?

**Comment by alexprice91** [comment] 2017-01-22 17:32
bump

**Comment by veedeo** [comment] 2017-01-23 08:49
does this branch "fdnhkj/react-native-maps" solve your issue?

**Comment by robotgo** [comment] 2017-03-02 13:30
@joshualcoffee i had the same issue 
`{"react-native": "0.41.2","react-native-maps": "0.13.0","react-native-router-flux": "3.37.0"}`
I followed gharwood's [recommendations](https://github.com/airbnb/react-native-maps/issues/453#issuecomment-265905846) and render map element only when scene with it is active:
```javascript
{ currentRoute === 'grounds'
              ? <Map objects={filteredGrounds} fetching={fetching} />
              : null
            }
```
`<Map />` is a wrapper around MapView.
To get current route with react-native-router-flux I connect Router to redux as explained [here](https://github.com/aksonov/react-native-router-flux/blob/master/docs/REDUX_FLUX.md)
This approach allows to save memory removing unactive maps from navigation stack.

**Comment by joshualcoffee** [comment] 2017-03-02 13:35
That will not work in all use cases. The best example I have is showing children of the same object type.  Lets say I have a "person" model that can be the child or parent of another person.  If i want to render a modal (or something along those lines) with the same component on top of the screen the issue will still happen.  

The only work around I could see is to have an internal state on each component that checks to see if the parent is visible.  However it gets ugly because you have to pass aroudn actions and events to handle the internal state.

**Comment by iiitmahesh** [comment] 2017-03-28 15:54
@joshualcoffee I have a same problem. How to slove this??

**Comment by kapilgp** [comment] 2017-04-03 16:48
Facing same issue me too...

on switching screens previous screen map is still there on top of new screen map.
using following modules

`"react": "15.4.2",
    "react-native": "0.42.3",
    "react-native-maps": "^0.13.1",
    "react-native-splash-screen": "^2.0.0",
    "react-navigation": "^1.0.0-beta.7"`

Can anyone provide me solution of it. I think it is best if there is any option for destroy previous map at the time of switching screen.

**Comment by joshualcoffee** [comment] 2017-04-03 16:52
If you are using redux you can solve this by creating a map container that has a state to render the map or not.  

The idea is to have a flag with the screen name and unique identifier.  So for us we used something like `customerShowScreeen#1123` 1123 is the id of the customer.  I then check to make sure the screen is active and the key matches the key we pass in to the props.  If everything is true I will render the component if it's false I will return null not rendering this component.  

This allowed us to use modals and other type of screen renderers without it interfering with the underlying code.

**Comment by ryankask** [comment] 2017-04-03 17:49
This issue was fixed but there was a regression in version 0.13.1 (see #1161 for details)

Please try downgrading to 0.13.0 to see if that fixes the issue.

**Comment by kapilgp** [comment] 2017-04-04 05:38
Thanks @ryankask :+1: 

It's working with 0.13.0. Hope it will resolve in next release :)

**Comment by privateOmega** [comment] 2017-04-18 14:44
Hey guys,
I am encountering the issue on the following setup. Has this bug been officially resolved or Is there any good workarounds.
React:15.4.2,RN:0.42.0,RNMaps:0.13.0,RNRouteFlux:3.38.0
Any help is much appreciated.

**Comment by delvedor** [comment] 2017-05-05 17:15
Same issue here:
```
react-native: v0.42.0
react-native-maps: v0.14.0
```

**Comment by ianaz** [comment] 2017-05-09 21:43
same issue
react-native: 0.42.0
react-native-maps: 0.15.0

**Comment by christopherdro** [comment] 2017-05-10 05:53
@delvedor @ianaz Care to try https://github.com/airbnb/react-native-maps/pull/1311 and see if that works for you?

**Comment by ianaz** [comment] 2017-05-10 06:56
@christopherdro oh cool! I'll try it as soon as i get back to the project and let you know :) Thanks!

**Comment by delvedor** [comment] 2017-05-11 16:40
@christopherdro I tried your solution and seems to fix the issue :)

**Comment by scotbond** [comment] 2017-06-12 18:11
The problem still occurs on Android 6.0.0 (API 23).
I am able to easily reproduce it with a fresh sample app having two screens, each with it's own MapView.
I'm using 'react-navigation' to navigate between them.

Can someone please test with Android 6 and report?

**Comment by ShivamKJJW** [comment] 2017-06-16 12:14
@scotbond You need to modify your package.json file to specify the latest commit as below:
`"react-native-maps": "git://github.com/olegpesok/react-native-maps.git#0c925244cf138905ca0a6d67894f0761c73eb28e"`
Also make sure your to change the app.gradle as specified by @pellepersson in his [comment](https://github.com/airbnb/react-native-maps/issues/453#issuecomment-243821801).

I did the same and it resolved from me.

**Comment by samthui** [comment] 2017-10-07 02:56
I have same problem & following @joshualcoffee did fix it.
Let say I have 2 scenes: A & B, both contain Map. Pushing B from A will display A's map on top of B's.
I solved it by hiding A's map before pushing B, and re-showing it after popping back to A.
That makes map blink, but at least solves the issue.

**Comment by fumiki** [comment] 2018-04-26 07:42
This still occurs for me.

```
"react-native": "^0.55.3"
"react-native-maps": "^0.21.0"
```
I tried on multiple versions.  
It seems to occur under 6.0.0.

5.1.0 - Genymotion => NG
6.0.0 - Genymotion => NG
6.0.1 - Actual Device => OK
7.0.0 - Genymotion => OK
8.0.0 - Genymotion => OK

**Comment by fcabrera23** [comment] 2018-08-17 16:00
Still having the same issue, any  solution?

**Comment by JuanMa06** [comment] 2018-08-17 16:58
@fcabrera23  me too!! We need a solution!!!

**Comment by fcabrera23** [comment] 2018-08-29 14:04
@fumiki  did you solve the problem? I have already tried all suggestions above, but none worked.

**Comment by fumiki** [comment] 2018-08-29 14:49
@fcabrera23 
My workaround is below.  
When the screen did disappear, hide MapView component by StyleSheet.  
(And show MapView when the screen will appear)  

`
<MapView
  style={this.state.isFocused ? styles.visible : styles.hidden}
>

const styles = StyleSheet.create({
  visible: {
    ...StyleSheet.absoluteFillObject
  },
  hidden: {
    height: 1,
    top: -1000
  }
});
`

this.state.isFocused is boolean for the screen is focused.  
In my case, I use react-navigation that can handle it.  
https://reactnavigation.org/docs/en/with-navigation-focus.html  
`
this.props.navigation.addListener("didBlur", () =>
  this.setState({ isFocused: false })
);
this.props.navigation.addListener("willFocus", () =>
  this.setState({ isFocused: true })
);
`
